// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/dx/study/github.com/lujiang618/study/cgo/builder/main.go:1:1
package main

// int sum(int a, int b) { return a+b; }
import _ "unsafe"

func main() {
	println(( /*line :7:10*/_Cfunc_sum /*line :7:14*/)(1, 1))
}
